import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>비오키친 어드민</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p>dkff</p>
    </div>
  )
}

export default Home
